# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d8a49424e95fae7f64875a210e68dcf6936ef23390d2bd1441c25e272e52bac0b8120051c4929812c594f4ba882bbde1b42fb41f26c5b76dc86bf5bc44e425

test:
  secret_key_base: 334afeb4ec05916dde9d89a64a3468c135265f12af8983d36b247266cdea885756075571864dd83480385011e28d49b598f4f9f5adb7654b3479e26896e1370a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
